export interface Car {
  id: string
  show_whatsapp_access: string
  body_condition: string
  whatsapp_number?: string
  mechanical_condition: string
  description: string
  make: string
  make_ar: string
  make_country_name: string
  model: string
  city: string
  body_style: string
  fuel_type: string
  transmission_type: string
  cylinders: string
  seller_type: string
  locale: string
  picture_title: string
  title: string
  country: string
  exterior_color: string
  year: number
  price: number
  currency: string
  km_driven: number
  fuelType: string
  transmission: string
  bodyType: string
  color: string
  pictures: string[]
  featured: boolean
}
